config/routes.rb
Rails.application.routes.draw do
  resources :sections do
    resources :food_items
  end
  resources :line_items
  resources :orders do
    member do
      get "thanks"
    end
  end

  root "home#index"
  get "contact" => "home#contact"
  get "menu" => "sections#index"
  get "cart" => "carts#show"
  get "order" => "orders#show"
  post "carts/add"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def item_count
    line_items.count
  end

  def total
    ordertotal = line_items.sum { |p| p.food_item.price * p.quantity }
    total = ordertotal + 20000
    total
  end
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :name, :price, presence: true
  belongs_to :section
  has_many :line_items, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :food_item
  belongs_to :order, optional: true
  validates :quantity, presence: true, numericality: {greater_than: 0}

  def name
    food_item.name
  end

  def totalprice
    food_item.price*quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def total
    line_items.sum { |p| p.food_item.price * p.quantity }
  end
end

app/models/section.rb
class Section < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :food_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :get_cart

  def get_cart
    return @cart if @cart
    Rails.logger.info "Loading cart from DB"
    if session[:cart_id]
      @cart = Cart.find session[:cart_id]
    else
      set_cart
    end
  end

  def set_cart
    @cart = Cart.create
    session[:cart_id] = @cart.id
    @cart
  end

  def destroy_cart
    session[:cart_id] = nil
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def add
    @cart = get_cart
    @cart.line_items.create line_item_params
    unless @cart.save
      flash[:error] = "There was an error with adding the item to your cart. Please try again."
    end
    redirect_back(fallback_location: menu_path)
  end

  def show
    @cart = get_cart
  end

  def line_item_params
    params.require(:line_item).permit(:food_item_id, :quantity)
  end

  def

  def total
    @cart = get_cart
    @cart.line_items
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :price, :description, :section_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def destroy
    line_item = LineItem.find(params[:id])
    line_item.destroy
    redirect_to cart_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    @order = Order.new order_params
    @order.line_items = get_cart.line_items
    @order.save
    # if @order.save
    #   destroy_cart
    #end
    redirect_to thanks_order_path(id: @order.id)
  end

  def order_params
    params.require(:order).permit(:name, :address, :phone)
  end

  def show  
  end

  def thanks
    @order = Order.find(params[:id])
    destroy_cart
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    unless params[:section]
      redirect_to menu_path(section: Section.first.id)
      return
    end

    @sections = Section.all
    section = Section.find(params[:section])
    @food_items = section.food_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_string_for(datetime)
    datetime.strftime("%A, %d %b %Y %l:%M %p")
 end

  def priceVND(price)
    number_to_currency(price, unit: "VND ")
  end

  def flasherize(key)
    case key.to_sym
      when :success then "success"
      when :error then "error"
      end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/show.html.erb
<div class="menu-header">
  <div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
      <a href="/"  class="item">
        Home
      </a>
      <a href="menu" class="item">
        Menu
      </a>
      <a href="contact" class="item">
        Contact Us
      </a>
      <div class ="right menu">
        <a href="cart" style="margin-top: 10px; margin-right: 10px; color: white">
          Items in your cart: <%= get_cart.item_count %>
          <i class="shopping basket icon" style="float: right; margin-left: 10px;"></i>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="contact">
  <div class="ui raised very padded text container segment" style="padding: 20px;">

    <div class="ui three steps">
      <div class="active step">
        <i class="food icon black"></i>
        <div class="content">
          <div class="title">Review Your Order</div>
        </div>
      </div>
      <div class="disabled step">
        <i class="truck icon"></i>
        <div class="content">
          <div class="title">Enter Delivery Info</div>
        </div>
      </div>
      <div class="disabled step">
        <i class="payment icon"></i>
        <div class="content">
          <div class="title">Your Food is on the Way!</div>
        </div>
      </div>
    </div>


    <div class="cart-header">
        <h1>Please review your order:</h1>
    </div>

    <table class="ui three column table">
      <thead>
        <tr><th>Item</th>
        <th>Quantity</th>
        <th>Total Price</th>
        <th>Action</th>
      </tr></thead>
      <tbody>
        <% @cart.line_items.each do |line_item| %>
          <tr>
            <td><%= line_item.name %></td>
            <td><%= line_item.quantity %></td>
            <td><%= priceVND(line_item.totalprice) %></td>
            <td><%= link_to "Delete", line_item_path(line_item), method: :delete %></td>
          </tr>
        <% end %>
        <tr>
            <td>Delivery Fee</td>
            <td></td>
            <td><%= priceVND(20000) %></td>
            <td></td>
          </tr>
      </tbody>
        <tfoot>
          <tr><th><strong>Total:</strong></th>
          <th></th>
          <th><strong><%= priceVND(@cart.total) %></strong></th>
          <th></th>
        </tr></tfoot>
    </table>

    <%= link_to "Proceed to Checkout", orders_path, method: :get, class: "ui secondary button" %>

  </div>
</div>

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_item_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :food_item_description %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.text_field :section_id, id: :food_item_section_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.section %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact.html.erb
<div class="menu-header">
  <div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
      <a href="/"  class="item">
        Home
      </a>
      <a href="menu" class="item">
        Menu
      </a>
      <a class="active item">
        Contact Us
      </a>
      <div class ="right menu">
        <a href="cart" class="<%= get_cart.item_count %>" style="margin-top: 10px; margin-right: 10px; color: white">
          Items in your cart: <%= get_cart.item_count %>
          <i class="shopping basket icon" style="float: right; margin-left: 10px;"></i>
        </a>
      </div>
    </div>
  </div>
</div>

<a href="cart" class="checkout-label hidden">
  <div class="ui pointing large label red" style="float: right; margin-right: 10px;">
              Click here to Checkout
  </div>
</a>

<div class="contact">
  <div class="ui raised very padded text container segment" style="padding: 20px;">
    <div class="contact-header">
        <h1>Contact Us</h1>
    </div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.0876497601485!2d106.73454675006404!3d10.804598761590537!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317526173f7a8e43%3A0x2a38505e4cdfdc21!2sBanh+Mi+362!5e0!3m2!1sen!2s!4v1501829776169" width="400" height="300" frameborder="0" style="border:0"></iframe>
    <div class="address">
    <address>
    <strong>Our Address: </strong>
    Thảo Điền, District 2, Ho Chi Minh, Vietnam
    </address>
    <tel>
    <strong>Phone Number: </strong>
    090 350 64 91
    </tel>
    </div>
  </div>
</div>
</div>

app/views/home/index.html.erb
<div class="menu-header">
  <div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
      <a class="active item">
        Home
      </a>
      <a href="menu" class="item">
        Menu
      </a>
      <a href="contact" class="item">
        Contact Us
      </a>
      <div class ="right menu">
        <a href="cart" class="<%= get_cart.item_count %>" style="margin-top: 10px; margin-right: 10px; color: white">
          Items in your cart: <%= get_cart.item_count %>
          <i class="shopping basket icon" style="float: right; margin-left: 10px;"></i>
        </a>
      </div>
    </div>
  </div>
</div>

<a href="cart" class="checkout-label hidden">
  <div class="ui pointing large label red" style="float: right; margin-right: 10px;">
              Click here to Checkout
  </div>
</a>

<div class="welcome">
  <div class="menu fourteen wide column">
    <div class="ui raised very padded text container segment">
      <%= image_tag "logo.png", class: "logo" %>
      <div class="welcome-header">
      <p>Banh Mi 362 is proudly serving customers since 1980.</p>
      <p>We only use fresh ingredients, ensuring traditional taste and highest quality.</p>
      </div>
      <div class="welcome-nav">
        <a href="menu">
        <button class="ui black animated button" tabindex="0" style="width: 111px;">
          <div class="visible content">Menu</div>
          <div class="hidden content">
            <i class="right arrow icon"></i>
          </div>
        </button>
        </a>
        <a href="contact">
          <button class="ui black animated button" tabindex="0">
              <div class="visible content">Contact Us</div>
              <div class="hidden content">
                <i class="right arrow icon"></i>
              </div>
          </button>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BanhMi362</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="menu-header">
  <div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
      <a href="/"  class="item">
        Home
      </a>
      <a href="menu" class="item">
        Menu
      </a>
      <a href="contact" class="item">
        Contact Us
      </a>
      <div class ="right menu">
        <a href="cart" style="margin-top: 10px; margin-right: 10px; color: white">
          Items in your cart: <%= get_cart.item_count %>
          <i class="shopping basket icon" style="float: right; margin-left: 10px;"></i>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="contact">
  <div class="ui raised very padded text container segment" style="padding: 20px;">

    <div class="ui three steps">
      <div class="disabled step">
        <i class="checkmark icon"></i>
        <div class="content">
          <div class="title">Review Your Order</div>
        </div>
      </div>
      <div class="active step">
        <i class="truck icon black"></i>
        <div class="content">
          <div class="title">Enter Delivery Info</div>
        </div>
      </div>
      <div class="disabled step">
        <i class="payment icon"></i>
        <div class="content">
          <div class="title">Your Food is on the Way!</div>
        </div>
      </div>
    </div>

    <div class="cart-header" style="margin-bottom: 20px;">
        <h1>Your details:</h1>
    </div>

    <%= form_for Order.new, html: {class: "ui form"} do |f| %>
      <div class="field">
        <label style="float: left;">Your Name:</label>
        <%= f.text_field :name, placeholder: "Your Name..." %>
      </div>
      <div class="field">
        <label style="float: left;">Your Phone Number:</label>
        <%= f.text_field :phone, placeholder: "Your Phone Number..." %>
      </div>
      <div class="field">
        <label style="float: left;">The Delivery Address:</label>
        <%= f.text_area :address, placeholder: "The Delivery Address..." %>
      </div>
      <%= f.submit "Place Your Order", class: "negative ui button" %>
    <% end %>

  </div>
</div>

app/views/orders/thanks.html.erb
<div class="menu-header">
  <div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
      <a href="/"  class="item">
        Home
      </a>
      <a href="/menu" class="item">
        Menu
      </a>
      <a href="/contact" class="item">
        Contact Us
      </a>
      <div class ="right menu">
        <a href="cart" style="margin-top: 10px; margin-right: 10px; color: white">
          Items in your cart: <%= get_cart.item_count %>
          <i class="shopping basket icon" style="float: right; margin-left: 10px;"></i>
        </a>
      </div>
    </div>
  </div>
</div>

    <div class="contact">
      <div class="ui raised very padded text container segment" style="padding: 20px;">


        <div class="ui three steps">
          <div class="disabled step">
            <i class="checkmark icon"></i>
            <div class="content">
              <div class="title">Review Your Order</div>
            </div>
          </div>
          <div class="disabled step">
            <i class="checkmark icon"></i>
            <div class="content">
              <div class="title">Enter Delivery Info</div>
            </div>
          </div>
          <div class="completed step">
            <i class="payment icon"></i>
            <div class="content">
              <div class="title">Your Food is on the Way!</div>
            </div>
          </div>
        </div>


        <div class="cart-header" style="margin-bottom: 20px;">
            <h1>Thank you <%= @order.name %>!</h1>
        </div>

        <div class="ui centered card">
          <div class="content">
            <div class="header">Your Order</div>
            <div class="description">
                <div>Order ID: #<%= @order.id %></div>
                <div>Order submitted: <%= date_string_for(@order.created_at) %> </div>
                <div>Total: <%= priceVND(@order.total) %></div>
                <div>Delivery address: <%= @order.address %></div><br>
                <div class="order">
                  You ordered:
                  <ul>
                    <% @order.line_items.each do |item| %>
                      <li> 
                        <%= item.quantity %>x <%= item.name %>
                      </li>
                    <% end %>
                  </ul>
                </div>
            </div>
          </div>
        </div>


    

  </div>
</div>

app/views/sections/index.html.erb
<div class="menu-header">
  <div class="ui inverted segment">
    <div class="ui inverted secondary pointing menu">
      <a href="/" class="item">
        Home
      </a>
      <a class="active item">
        Menu
      </a>
      <a href="contact" class="item">
        Contact Us
      </a>
      <div class ="right menu">
        <a href="cart" class="<%= get_cart.item_count %>" style="margin-top: 10px; margin-right: 10px; color: white">
          Items in your cart: <%= get_cart.item_count %>
          <i class="shopping basket icon" style="float: right; margin-left: 10px;"></i>
        </a>
      </div>
    </div>
  </div>
</div>
<a href="cart" class="checkout-label hidden">
  <div class="ui pointing large label red" style="float: right; margin-right: 10px;">
              Click here to Checkout
  </div>
</a>
<div class="menu">
  <div class="ui raised padded text container segment">
    <% flash.each do |key, value| %>
      <div class="ui <%= flasherize(key) %> message">
        <div class="header">
          Oh No!
        </div>
        <p><%= value %></p>
      </div>
    <% end %>
    <div class="ui top attached tabular menu">
      <% @sections.each do |section| %>
        <%= link_to section.name, menu_path(section: section.id), 
            class: "item #{'active' if params[:section] == section.id.to_s}" %>
      <% end %>
    </div>
    <div class="ui bottom attached segment">
    <div class="fooditems">
    <div class="ui divided items">
    <% if @food_items.present? %>
      <% @food_items.each do |item|%>
          <div class="item">
            <div class="ui small image">
              <%= image_tag "banhmi-250.jpg", class: "itempic" %>
            </div>
            <div class="content">
              <div class="header"><%= item.name %></div>
              <div class="meta">
                <span class="price"><%= number_to_currency(item.price, unit: "VND ") %></span>
              </div>
              <div class="description">
                <%= item.description %>
              </div>
              <div class="extra">
                <%= form_for LineItem.new(food_item: item), url: carts_add_path do |f| %>
                  <%= f.hidden_field :food_item_id %>
                    <div class="ui action input right floated">
                      <%= f.number_field :quantity, min: "1", value: "1", style: "width: 60px;", class: "rigth floated" %>
                      <button class="ui black labeled icon button">
                        <i class="cart icon"></i>
                        Add to Cart
                      </button>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>